project:
  type: website

website:
  title: "Notebook thing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - eda.qmd
      - model-stuff.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



