project:
  type: website

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Notebook thing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - eda.qmd
      - model-stuff.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



